/* Generated By:JavaCC: Do not edit this line. MindGRAF_ParserConstants.java */
package edu.guc.mind_graf.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MindGRAF_ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int currContext = 6;
  /** RegularExpression Id. */
  int GetAttitudeNames = 7;
  /** RegularExpression Id. */
  int MODE1 = 8;
  /** RegularExpression Id. */
  int MODE2 = 9;
  /** RegularExpression Id. */
  int MODE3 = 10;
  /** RegularExpression Id. */
  int N = 11;
  /** RegularExpression Id. */
  int IDENTIFIER = 12;
  /** RegularExpression Id. */
  int LETTER = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int ANDOR_THRESH = 15;
  /** RegularExpression Id. */
  int WHENDO_DOIF = 16;
  /** RegularExpression Id. */
  int QUANTIFIER = 17;
  /** RegularExpression Id. */
  int ENTAILMENT = 18;
  /** RegularExpression Id. */
  int VARIABLE = 19;
  /** RegularExpression Id. */
  int WFF_NAME = 20;
  /** RegularExpression Id. */
  int STRING = 21;
  /** RegularExpression Id. */
  int PREDICATE_NAME_BRACKET = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "<NUMBER>",
    "\"get-curr-context\"",
    "\"get-attitudes\"",
    "\"set-mode-1\"",
    "\"set-mode-2\"",
    "\"set-mode-3\"",
    "<N>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<ANDOR_THRESH>",
    "<WHENDO_DOIF>",
    "\"forall(\"",
    "<ENTAILMENT>",
    "\"?\"",
    "<WFF_NAME>",
    "<STRING>",
    "<PREDICATE_NAME_BRACKET>",
    "\"g{\"",
    "\",\"",
    "\"}\"",
    "\")\"",
    "\"(\"",
    "\"=>\"",
    "\"{\"",
    "\"snsequence{\"",
    "\"attitude{\"",
    "\"achieve{\"",
    "\"doone{\"",
    "\"do-one{\"",
    "\"guard{\"",
    "\"snif{\"",
    "\"sniterate{\"",
    "\"define-frame\"",
    "\"define-semantic\"",
    "\"add-bridge\"",
    "\"[\"",
    "\"]\"",
    "\"describe-context\"",
    "\"remove-from-context\"",
    "\"add-to-context\"",
    "\"back-infer\"",
    "\"forward-infer\"",
    "\"get-contexts\"",
    "\"set-curr-context\"",
    "\"custom-method\"",
    "\".\"",
    "\";\"",
    "\":\"",
    "\"<\"",
    "\">\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"-\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"\\\\\"",
    "\"=\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"!\"",
    "\"%\"",
    "\"@\"",
    "\"#\"",
    "\"$\"",
    "\"~\"",
    "\"set-uvbr\"",
    "\"set-attitudes\"",
    "\"define-context\"",
    "\"set-telescopable \"",
    "\"set-closed-consequence \"",
    "\"set-closed-conjunction \"",
    "\"set-consistent-attitudes \"",
  };

}
