/* Generated By:JavaCC: Do not edit this line. MindGRAF_ParserConstants.java */
package edu.guc.mind_graf.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MindGRAF_ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int TIMES = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int LPAREN = 9;
  /** RegularExpression Id. */
  int RPAREN = 10;
  /** RegularExpression Id. */
  int PRINT = 11;
  /** RegularExpression Id. */
  int currContext = 12;
  /** RegularExpression Id. */
  int ADD = 13;
  /** RegularExpression Id. */
  int SPACE = 14;
  /** RegularExpression Id. */
  int GetAttitudeNames = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<NUMBER>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"print\"",
    "\"get-curr-context\"",
    "\"ADD\"",
    "\" \"",
    "\"get-attitudes\"",
    "\"\"",
  };

}
