/* Generated By:JavaCC: Do not edit this line. MindGRAF_ParserConstants.java */
package edu.guc.mind_graf.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MindGRAF_ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int currContext = 6;
  /** RegularExpression Id. */
  int GetAttitudeNames = 7;
  /** RegularExpression Id. */
  int MODE1 = 8;
  /** RegularExpression Id. */
  int MODE2 = 9;
  /** RegularExpression Id. */
  int MODE3 = 10;
  /** RegularExpression Id. */
  int N = 11;
  /** RegularExpression Id. */
  int BOOL = 12;
  /** RegularExpression Id. */
  int IDENTIFIER = 13;
  /** RegularExpression Id. */
  int LETTER = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int ANDOR_THRESH = 16;
  /** RegularExpression Id. */
  int VARIABLE = 17;
  /** RegularExpression Id. */
  int WFF_NAME = 18;
  /** RegularExpression Id. */
  int STRING = 19;
  /** RegularExpression Id. */
  int PREDICATE_NAME_BRACKET = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "<NUMBER>",
    "\"get-curr-context\"",
    "\"get-attitudes\"",
    "\"set-mode-1\"",
    "\"set-mode-2\"",
    "\"set-mode-3\"",
    "<N>",
    "<BOOL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<ANDOR_THRESH>",
    "\"?\"",
    "<WFF_NAME>",
    "<STRING>",
    "<PREDICATE_NAME_BRACKET>",
    "\",\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"define-context \"",
    "\"add-to-context\"",
    "\"set-uvbr\"",
    "\"set-attitudes\"",
    "\"set-telescopable \"",
    "\"set-closed-consequence \"",
    "\"set-closed-conjunction \"",
    "\"set-consistent-attitudes \"",
  };

}
